<?php
require_once '../../Database/db_config.php';
$customers = [];

// Pagination logic
$page = isset($_GET['page']) ? max(1, intval($_GET['page'])) : 1;
$per_page = isset($_GET['per_page']) ? max(1, intval($_GET['per_page'])) : 10;
$offset = ($page - 1) * $per_page;

// Get total count for pagination
$total_sql = "SELECT COUNT(*) as total FROM Customer WHERE CustomerName NOT LIKE '%-'";
$total_result = $conn->query($total_sql);
$total_customers = 0;
if ($total_result && $row = $total_result->fetch_assoc()) {
    $total_customers = (int)$row['total'];
}

// Exclude customers whose CustomerName ends with '-'
$sql = "SELECT c.*, 
    (SELECT COUNT(*) FROM Transaction t WHERE t.CustomerID = c.CustomerID) as orders
FROM Customer c 
WHERE c.CustomerName NOT LIKE '%-' 
ORDER BY c.CustomerID DESC
LIMIT $per_page OFFSET $offset";
$result = $conn->query($sql);
if ($result && $result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $customers[] = [
            'id' => $row['CustomerID'],
            'name' => $row['CustomerName'],
            'phone' => $row['CustomerNumber'],
            'address' => $row['CustomerAddress'],
            'orders' => (int)$row['orders']
        ];
    }
}

if (isset($_GET['fetch'])) {
    header('Content-Type: application/json');
    echo json_encode([
        'customers' => $customers,
        'total' => $total_customers,
        'per_page' => $per_page
    ]);
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clients - RJane Water Refilling Station</title>
    <link rel="stylesheet" href="../../Css/customers.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="Sidebar.html">
</head>

<body>
    <div id="navbar"></div>

    <script>
        fetch('Sidebar.html')
            .then(response => response.text())
            .then(data => {
                document.getElementById('navbar').innerHTML = data;
            });
    </script>
    <div class="main-content">


        <!-- Client Management Header -->
        <div class="dashboard-header">
            <h2>Customer Management</h2>
            <button class="primary-btn" id="newClientBtn">
                <i class="fas fa-plus"></i> New Customer
            </button>
        </div>

        <!-- Filter Options -->
        <div class="filters-container">
            <div class="filter-options">
                <select class="filter-select">
                    <option>All Clients</option>
                </select>
            </div>
            <div class="view-options">
                <button class="view-btn active" data-view="grid"><i class="fas fa-th"></i></button>
                <button class="view-btn" data-view="list"><i class="fas fa-list"></i></button>
            </div>
        </div>

        <!-- Client Grid View -->
        <div class="client-grid" id="gridView">
            <!-- Client Cards will be generated by JavaScript -->
        </div>

        <!-- Client List View (Hidden by Default) -->
        <div class="client-list" id="listView" style="display: none;">
            <table class="clients-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Contact</th>
                        <th>Address</th>
                        <th>Total Orders</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody id="clientTableBody">
                    <!-- Table rows will be generated by JavaScript -->
                </tbody>
            </table>
        </div>

        <!-- Pagination -->
        <div class="pagination"></div>
    </div>

    <!-- Add Client Modal -->
    <div class="modal" id="addClientModal">
        <div class="modal-content">
            <div class="modal-header">
                <h3>Add New Client</h3>
                <button class="close-btn" id="closeModal">&times;</button>
            </div>
            <div class="modal-body">
                <form id="newClientForm">
                    <div class="form-group">
                        <label for="CustomerName">Customer Name</label>
                        <input type="text" id="CustomerName" name="CustomerName" required>
                    </div>
                    <div class="form-group">
                        <label for="CustomerNumber">Contact Number</label>
                        <input type="tel" id="CustomerNumber" name="CustomerNumber" required>
                    </div>
                    <div class="form-group">
                        <label for="CustomerAddress">Address</label>
                        <input type="text" id="CustomerAddress" name="CustomerAddress" required>
                    </div>
                    <!-- Add form actions -->
                    <div class="form-actions">
                        <button type="button" class="secondary-btn" id="cancelBtn">Cancel</button>
                        <button type="submit" class="primary-btn">Save Customer</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Edit Client Modal -->
    <div class="modal" id="editClientModal">
        <div class="modal-content">
            <div class="modal-header">
                <h3>Edit Client</h3>
                <button class="close-btn" id="closeEditModal">&times;</button>
            </div>
            <div class="modal-body">
                <form id="editClientForm">
                    <input type="hidden" id="EditCustomerID" name="CustomerID">
                    <div class="form-group">
                        <label for="EditCustomerName">Customer Name</label>
                        <input type="text" id="EditCustomerName" name="CustomerName" required>
                    </div>
                    <div class="form-group">
                        <label for="EditCustomerNumber">Contact Number</label>
                        <input type="tel" id="EditCustomerNumber" name="CustomerNumber" required>
                    </div>
                    <div class="form-group">
                        <label for="EditCustomerAddress">Address</label>
                        <input type="text" id="EditCustomerAddress" name="CustomerAddress" required>
                    </div>
                    <div class="form-actions">
                        <button type="button" class="secondary-btn" id="cancelEditBtn">Cancel</button>
                        <button type="submit" class="primary-btn">Update Customer</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        // Pagination state
        let currentPage = 1;
        let totalPages = 1;
        const perPage = 10;
        const paginationContainer = document.querySelector('.pagination');

        // Fetch customers from server with pagination
        function fetchCustomers(page = 1) {
            fetch(`customers.php?fetch=1&page=${page}&per_page=${perPage}`)
                .then(response => response.json())
                .then(data => {
                    clients = data.customers;
                    totalPages = Math.ceil(data.total / perPage) || 1;
                    renderGridView();
                    renderListView();
                    renderPagination();
                });
        }

        // Render pagination buttons
        function renderPagination() {
            paginationContainer.innerHTML = '';
            // Previous button
            const prevBtn = document.createElement('button');
            prevBtn.className = 'pagination-btn';
            prevBtn.innerHTML = '<i class="fas fa-chevron-left"></i>';
            prevBtn.disabled = currentPage === 1;
            prevBtn.onclick = () => changePage(currentPage - 1);
            paginationContainer.appendChild(prevBtn);

            // Page number buttons
            for (let i = 1; i <= totalPages; i++) {
                const pageBtn = document.createElement('button');
                pageBtn.className = 'pagination-btn' + (i === currentPage ? ' active' : '');
                pageBtn.textContent = i;
                pageBtn.onclick = () => changePage(i);
                paginationContainer.appendChild(pageBtn);
            }

            // Next button
            const nextBtn = document.createElement('button');
            nextBtn.className = 'pagination-btn';
            nextBtn.innerHTML = '<i class="fas fa-chevron-right"></i>';
            nextBtn.disabled = currentPage === totalPages;
            nextBtn.onclick = () => changePage(currentPage + 1);
            paginationContainer.appendChild(nextBtn);
        }

        function changePage(page) {
            if (page < 1 || page > totalPages) return;
            currentPage = page;
            fetchCustomers(currentPage);
        }

        // Load customers from PHP
        let clients = <?php echo json_encode($customers); ?>;

        // DOM Elements
        const gridView = document.getElementById('gridView');
        const listView = document.getElementById('listView');
        const clientTableBody = document.getElementById('clientTableBody');
        const viewButtons = document.querySelectorAll('.view-btn');
        const addClientModal = document.getElementById('addClientModal');
        const newClientBtn = document.getElementById('newClientBtn');
        const closeModalBtn = document.getElementById('closeModal');
        const cancelBtn = document.getElementById('cancelBtn');
        const newClientForm = document.getElementById('newClientForm');

        // Initialize the page
        document.addEventListener('DOMContentLoaded', function () {
            fetchCustomers(1);
            setupEventListeners();
        });

        // Render client cards in grid view
        function renderGridView() {
            gridView.innerHTML = '';

            clients.forEach(client => {
                const card = document.createElement('div');
                card.className = 'client-card';

                const firstLetter = client.name.charAt(0);

                card.innerHTML = `
            <div class="client-card-header">
                <div class="client-avatar"><span>${firstLetter}</span></div>
            </div>
            <div class="client-card-body">
                <h3>${client.name}</h3>
                <p><i class="fas fa-phone"></i> ${client.phone}</p>
                <p><i class="fas fa-location-dot"></i> ${client.address}</p>
            </div>
            <div class="client-card-footer">
                <div class="client-stats" style="justify-content: center;">
                    <div>
                        <span>Total Orders</span>
                        <h4>${client.orders}</h4>
                    </div>
                </div>
                <div class="client-actions">
                    <button title="Edit" class="edit-btn" data-id="${client.id}"><i class="fas fa-edit"></i></button>
                    <button title="Delete" class="delete-btn" data-id="${client.id}"><i class="fas fa-trash"></i></button>
                </div>
            </div>
        `;

                gridView.appendChild(card);
            });
        }

        // Render client data in table view
        function renderListView() {
            clientTableBody.innerHTML = '';

            clients.forEach(client => {
                const row = document.createElement('tr');

                row.innerHTML = `
            <td>${client.name}</td>
            <td>${client.phone}</td>
            <td>${client.address}</td>
            <td>${client.orders}</td>
            <td>
                <div class="action-buttons">
                    <button title="Edit" class="edit-btn" data-id="${client.id}"><i class="fas fa-edit"></i></button>
                    <button title="Delete" class="delete-btn" data-id="${client.id}"><i class="fas fa-trash"></i></button>
                </div>
            </td>
        `;

                clientTableBody.appendChild(row);
            });
        }

        // Setup event listeners
        function setupEventListeners() {
            // View toggle buttons
            viewButtons.forEach(button => {
                button.addEventListener('click', function () {
                    const viewType = this.getAttribute('data-view');

                    // Update active button
                    viewButtons.forEach(btn => btn.classList.remove('active'));
                    this.classList.add('active');

                    // Show the selected view
                    if (viewType === 'grid') {
                        gridView.style.display = 'grid';
                        listView.style.display = 'none';
                    } else {
                        gridView.style.display = 'none';
                        listView.style.display = 'block';
                    }
                });
            });

            // Modal functionality
            newClientBtn.addEventListener('click', openModal);
            closeModalBtn.addEventListener('click', closeModal);
            cancelBtn.addEventListener('click', closeModal);

            // Close modal when clicking outside
            window.addEventListener('click', function (event) {
                if (event.target === addClientModal) {
                    closeModal();
                }
            });

            // Form submission
            newClientForm.addEventListener('submit', function (event) {
                event.preventDefault();

                const formData = {
                    name: document.getElementById('CustomerName').value,
                    phone: document.getElementById('CustomerNumber').value,
                    address: document.getElementById('CustomerAddress').value
                };

                try {
                    if (validateClientData(formData)) {
                        // AJAX request to add customer
                        fetch('../Controllers/add_customer.php', {
                            method: 'POST',
                            headers: { 'Content-Type': 'application/json' },
                            body: JSON.stringify(formData)
                        })
                        .then(response => response.json())
                        .then(data => {
                            if (data.success) {
                                // Reload customers
                                fetchCustomers();
                                showNotification('Customer added successfully!');
                                closeModal();
                                newClientForm.reset();
                            } else {
                                showNotification(data.message || 'Failed to add customer', 'error');
                            }
                        })
                        .catch(() => showNotification('Server error', 'error'));
                    }
                } catch (error) {
                    showNotification(error.message, 'error');
                }
            });

            // Edit and Delete buttons (delegated)
            document.addEventListener('click', function(e) {
                if (e.target.closest('.edit-btn')) {
                    const id = e.target.closest('.edit-btn').dataset.id;
                    openEditModal(id);
                }
                if (e.target.closest('.delete-btn')) {
                    const id = e.target.closest('.delete-btn').dataset.id;
                    deleteCustomer(id);
                }
            });

            // Edit modal functionality
            const editClientModal = document.getElementById('editClientModal');
            const closeEditModalBtn = document.getElementById('closeEditModal');
            const cancelEditBtn = document.getElementById('cancelEditBtn');
            closeEditModalBtn.addEventListener('click', closeEditModal);
            cancelEditBtn.addEventListener('click', closeEditModal);
            window.addEventListener('click', function (event) {
                if (event.target === editClientModal) {
                    closeEditModal();
                }
            });

            // Edit form submission
            document.getElementById('editClientForm').addEventListener('submit', function(event) {
                event.preventDefault();
                const formData = {
                    id: document.getElementById('EditCustomerID').value,
                    name: document.getElementById('EditCustomerName').value,
                    phone: document.getElementById('EditCustomerNumber').value,
                    address: document.getElementById('EditCustomerAddress').value
                };
                try {
                    if (validateClientData(formData)) {
                        fetch('../Controllers/update_customer.php', {
                            method: 'POST',
                            headers: { 'Content-Type': 'application/json' },
                            body: JSON.stringify(formData)
                        })
                        .then(response => response.json())
                        .then(data => {
                            if (data.success) {
                                fetchCustomers();
                                showNotification('Customer updated successfully!');
                                closeEditModal();
                            } else {
                                showNotification(data.message || 'Failed to update customer', 'error');
                            }
                        })
                        .catch(() => showNotification('Server error', 'error'));
                    }
                } catch (error) {
                    showNotification(error.message, 'error');
                }
            });
        }

        // Add this function before the form submission handler
        function validateClientData(data) {
            // Accepts only 09XXXXXXXXX (11 digits)
            const phoneRegex = /^09\d{9}$/;

            if (data.name.length < 2) {
                throw new Error('Name must be at least 2 characters long');
            }

            if (!phoneRegex.test(data.phone)) {
                throw new Error('Phone number must start with 09 and be 11 digits');
            }

            if (data.address.length < 5) {
                throw new Error('Please enter a valid address');
            }

            return true;
        }

        // Open modal function
        function openModal() {
            addClientModal.classList.add('show');
            document.body.style.overflow = 'hidden'; // Prevent scrolling
        }

        // Close modal function
        function closeModal() {
            addClientModal.classList.remove('show');
            document.body.style.overflow = ''; // Re-enable scrolling
        }

        // Open edit modal function
        function openEditModal(id) {
            const client = clients.find(c => c.id == id);
            if (!client) return;
            document.getElementById('EditCustomerID').value = client.id;
            document.getElementById('EditCustomerName').value = client.name;
            document.getElementById('EditCustomerNumber').value = client.phone;
            document.getElementById('EditCustomerAddress').value = client.address;
            document.getElementById('editClientModal').classList.add('show');
            document.body.style.overflow = 'hidden';
        }

        // Close edit modal function
        function closeEditModal() {
            document.getElementById('editClientModal').classList.remove('show');
            document.body.style.overflow = '';
        }

        // Delete customer function
        function deleteCustomer(id) {
            if (!confirm('Are you sure you want to delete this customer?')) return;
            fetch('../Controllers/delete_customer.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ id })
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    fetchCustomers();
                    showNotification('Customer deleted successfully!');
                } else {
                    showNotification(data.message || 'Failed to delete customer', 'error');
                }
            })
            .catch(() => showNotification('Server error', 'error'));
        }

        // Show notification function
        function showNotification(message, type = 'success') {
            const notification = document.createElement('div');
            notification.className = 'notification';
            notification.innerHTML = `
        <div class="notification-content">
            <i class="fas fa-${type === 'success' ? 'check-circle' : 'exclamation-circle'}"></i>
            <span>${message}</span>
        </div>
    `;

            // Add styles
            notification.style.position = 'fixed';
            notification.style.top = '20px';
            notification.style.right = '20px';
            notification.style.backgroundColor = type === 'success' ? 'var(--success)' : 'var(--error)';
            notification.style.color = 'white';
            notification.style.padding = '12px 20px';
            notification.style.borderRadius = 'var(--border-radius)';
            notification.style.boxShadow = '0 4px 12px rgba(0, 0, 0, 0.1)';
            notification.style.display = 'flex';
            notification.style.alignItems = 'center';
            notification.style.zIndex = '2000';
            notification.style.transform = 'translateY(-20px)';
            notification.style.opacity = '0';
            notification.style.transition = 'all 0.3s ease';

            // Add to document
            document.body.appendChild(notification);

            // Show notification
            setTimeout(() => {
                notification.style.transform = 'translateY(0)';
                notification.style.opacity = '1';
            }, 100);

            // Remove after delay
            setTimeout(() => {
                notification.style.transform = 'translateY(-20px)';
                notification.style.opacity = '0';
                setTimeout(() => {
                    document.body.removeChild(notification);
                }, 300);
            }, 3000);
        }


    </script>


</body>

</html>